#!/usr/bin/env bun
/**
 * Walks packages/web/dist and writes an inlined asset map for the CLI embed path.
 * Output: packages/opencode/src/generated/opencode-web-ui.gen.ts
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

export type EmbeddedAsset = {
  mime: string
  encoding: "utf8" | "base64"
  body: string
}

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const webRoot = path.resolve(__dirname, "..")
const distDir = path.join(webRoot, "dist")
const outFile = path.resolve(webRoot, "../opencode/src/generated/opencode-web-ui.gen.ts")

const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".ico": "image/x-icon",
  ".map": "application/json",
  ".txt": "text/plain; charset=utf-8",
}

const TEXT_EXT = new Set([".html", ".js", ".mjs", ".css", ".json", ".svg", ".txt", ".map"])

function walk(dir: string, base = dir): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true })
  const files: string[] = []
  for (const entry of entries) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...walk(full, base))
      continue
    }
    if (entry.isFile()) files.push(path.relative(base, full))
  }
  return files
}

function mimeFor(filePath: string) {
  const ext = path.extname(filePath).toLowerCase()
  return MIME[ext] ?? "application/octet-stream"
}

export function buildAssetMap(root: string): Record<string, EmbeddedAsset> {
  if (!fs.existsSync(root)) {
    throw new Error(`Web dist not found at ${root}. Run vite build first.`)
  }
  const files = walk(root)
  if (!files.includes("index.html")) {
    throw new Error(`index.html missing from ${root}`)
  }

  const map: Record<string, EmbeddedAsset> = {}
  for (const rel of files) {
    const abs = path.join(root, rel)
    const key = rel.split(path.sep).join("/")
    const ext = path.extname(rel).toLowerCase()
    const buf = fs.readFileSync(abs)
    if (TEXT_EXT.has(ext)) {
      map[key] = {
        mime: mimeFor(rel),
        encoding: "utf8",
        body: buf.toString("utf8"),
      }
    } else {
      map[key] = {
        mime: mimeFor(rel),
        encoding: "base64",
        body: buf.toString("base64"),
      }
    }
  }
  return map
}

export function renderGenModule(map: Record<string, EmbeddedAsset>) {
  const payload = JSON.stringify(map, null, 2)
  return `// Generated by packages/web/script/generate-ui-gen.ts — do not edit.
export type EmbeddedAsset = {
  mime: string
  encoding: "utf8" | "base64"
  body: string
}

const assets: Record<string, EmbeddedAsset> = ${payload}

export default assets
`
}

if (import.meta.main) {
  const map = buildAssetMap(distDir)
  fs.mkdirSync(path.dirname(outFile), { recursive: true })
  fs.writeFileSync(outFile, renderGenModule(map))
  console.log(`Wrote ${outFile} (${Object.keys(map).length} assets)`)
}
